.TH METASERVER SECTION "July 23, 2002"
.SH NAME
metaserver \- A simple napster metaserver. Redirects clients to a specific set of servers.
.SH SYNOPSIS
.B metaserver
.RI [ -v ] [ -l IP ] [ -p <port> ] [ host:port ... ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B metaserver
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page (yet).
.PP
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.TP
.B \-l
IP listen only on interface for IP.
.TP
.B \-p <port>
Listen for connection on <port> (default is 8875).
.SH SEE ALSO
.BR opennap (1).

.SH AUTHOR
This manual page was written by Johan Schurer <leodav@users.sf.net>,
for the Debian GNU/Linux system (but may be used by others).
